### PR TITLE
Create Fried-Egg.md

### PR DESCRIPTION
**Pull request by vielmetti**
Needs formatting and recipe-patterning restructuring; this is straight from @vielmetti/sandwich

### CODE REVIEW

**Comment by bazbt3** [comment]
I almost haven't got a clue what I'm doing - my git is very rusty and was only at a rudimentary level anyway.

See Laura Fisher on App.net - my inspiration to fork the repo. :)

**Comment by vielmetti** [comment]
Thanks!

Long ago there was a Usenet Cookbook (from mod.recipes), so using version control on a cookbook is a great idea.

Also, sandwiches, can't argue with that.

**Comment by bazbt3** [comment]
This has graduated from 'just a bit of fun' to 'quite interesting'. Thanks to you!

Honestly though, I don't know where I'm going with the this/mine; it might all be a flash in the pan. ;)

**Comment by vielmetti** [comment]
I don't know where this goes to either, but of course it's more fun to cook
with someone else than by yourself.

On Thu, Dec 10, 2015 at 3:43 PM, bazbt3 notifications@github.com wrote:

> This has graduated from 'just a bit of fun' to 'quite interesting'. Thanks
> to you!
> 
> Honestly though, I don't know where I'm going with the this/mine; it might
> all be a flash in the pan. ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bazbt3/recipes/pull/2#issuecomment-163744165.

## 

Edward Vielmetti +1 734 330 2465
edward.vielmetti@gmail.com

**Comment by bazbt3** [comment]
True.  The App.net conversation earlier today that prompted [my blog post](http://bazbt3.re-app.net/2015/12/10/git-sandwiches/) just sparked that 'something.'   (App.net provides my inspiration when my family doesn't.)

**Pull request merged**
